[font]
size = 14.0
offset.y = 10

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[font.italic]
family = "Agave Nerd Font"
style = "Italic"

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[window.dimensions]
columns = 120
lines = 25

[window]
opacity = 0.97
padding.x = 0
padding.y = 0
dynamic_padding = false


[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
